### ISSUE TITLE
CI is broken

### ISSUE THREAD

**Issue by rfuest** [embedded-graphics/tinytga#17]
@jamwaffles Do you have any idea why CI isn't working at the moment? It did work correctly in the PR, but fails on the master branch. At first I suspected this might be a temporary problem, but it seems to be persistent.

**Comment by jamwaffles** [comment]
Very strange... the deploy key CircleCI uses vanished from Github's side. I've reauthed through Circle's UI and it looks like it's working now. Thanks for letting me know.

**Comment by rfuest** [comment]
> Thanks for letting me know.

Thanks for fixing it so quickly.

**Comment by jamwaffles** [comment]
Any time :)
